name = "tagger"
alias = ""
project_type = "programming"
tags = ["cli", "rust", "software development"]
date_created = "2024-12-24T18:47:05.250461490+09:00"
date_modified = "2024-12-26T16:00:02.312499122+09:00"
notes = []
git_url = "https://github.com/johnjallday/tagger.git"
